// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1G2r5-Eezg4zFSJj8ICWgf0GLdf1vcS0',
    appId: '1:642220695567:web:c5aecf209d9db70206837a',
    messagingSenderId: '642220695567',
    projectId: 'rewear-crowd',
    authDomain: 'rewear-crowd.firebaseapp.com',
    storageBucket: 'rewear-crowd.appspot.com',
    measurementId: 'G-ZH8KQQKJ4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzjCCgDKo6I26atZbWXeohZ5K8kDurJU',
    appId: '1:642220695567:android:d79bef2b52ff7e7a06837a',
    messagingSenderId: '642220695567',
    projectId: 'rewear-crowd',
    storageBucket: 'rewear-crowd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrJlP95vxsZ1wA2-jxH8B-fl3ETzF8n4',
    appId: '1:642220695567:ios:7440a5807e111bba06837a',
    messagingSenderId: '642220695567',
    projectId: 'rewear-crowd',
    storageBucket: 'rewear-crowd.appspot.com',
    androidClientId: '642220695567-6noh53cgi3rbiq7ase68252vgc55spld.apps.googleusercontent.com',
    iosClientId: '642220695567-rokm8sr50soblat2n42m1fpa9lmfspq1.apps.googleusercontent.com',
    iosBundleId: 'com.rewear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrJlP95vxsZ1wA2-jxH8B-fl3ETzF8n4',
    appId: '1:642220695567:ios:7440a5807e111bba06837a',
    messagingSenderId: '642220695567',
    projectId: 'rewear-crowd',
    storageBucket: 'rewear-crowd.appspot.com',
    androidClientId: '642220695567-6noh53cgi3rbiq7ase68252vgc55spld.apps.googleusercontent.com',
    iosClientId: '642220695567-rokm8sr50soblat2n42m1fpa9lmfspq1.apps.googleusercontent.com',
    iosBundleId: 'com.rewear',
  );
}
