class Autogenerated {
  bool? _login;
  String? _userId;
  String? _userToken;
  String? _qrUrl;
  List<String>? _specialPackage;
  List<ChildMembers>? _childMembers;
  String? _age;
  String? _userFirstName;
  String? _userLastName;
  int? _basicPercentage;
  int? _emergencyPercentage;
  int? _medicalPercentage;
  int? _totalPercentage;
  List<String>? _accessToken;

  Autogenerated(
      {bool? login,
      String? userId,
      String? userToken,
      String? qrUrl,
      List<String>? specialPackage,
      List<ChildMembers>? childMembers,
      String? age,
      String? userFirstName,
      String? userLastName,
      int? basicPercentage,
      int? emergencyPercentage,
      int? medicalPercentage,
      int? totalPercentage,
      List<String>? accessToken}) {
    if (login != null) {
      _login = login;
    }
    if (userId != null) {
      _userId = userId;
    }
    if (userToken != null) {
      _userToken = userToken;
    }
    if (qrUrl != null) {
      _qrUrl = qrUrl;
    }
    if (specialPackage != null) {
      _specialPackage = specialPackage;
    }
    if (childMembers != null) {
      _childMembers = childMembers;
    }
    if (age != null) {
      _age = age;
    }
    if (userFirstName != null) {
      _userFirstName = userFirstName;
    }
    if (userLastName != null) {
      _userLastName = userLastName;
    }
    if (basicPercentage != null) {
      _basicPercentage = basicPercentage;
    }
    if (emergencyPercentage != null) {
      _emergencyPercentage = emergencyPercentage;
    }
    if (medicalPercentage != null) {
      _medicalPercentage = medicalPercentage;
    }
    if (totalPercentage != null) {
      _totalPercentage = totalPercentage;
    }
    if (accessToken != null) {
      _accessToken = accessToken;
    }
  }

  // ignore: unnecessary_getters_setters
  bool? get login => _login;
  set login(bool? login) => _login = login;
  String? get userId => _userId;
  set userId(String? userId) => _userId = userId;
  String? get userToken => _userToken;
  set userToken(String? userToken) => _userToken = userToken;
  String? get qrUrl => _qrUrl;
  set qrUrl(String? qrUrl) => _qrUrl = qrUrl;
  List<String>? get specialPackage => _specialPackage;
  set specialPackage(List<String>? specialPackage) =>
      _specialPackage = specialPackage;
  List<ChildMembers>? get childMembers => _childMembers;
  set childMembers(List<ChildMembers>? childMembers) =>
      _childMembers = childMembers;
  String? get age => _age;
  set age(String? age) => _age = age;
  String? get userFirstName => _userFirstName;
  set userFirstName(String? userFirstName) => _userFirstName = userFirstName;
  String? get userLastName => _userLastName;
  set userLastName(String? userLastName) => _userLastName = userLastName;
  int? get basicPercentage => _basicPercentage;
  set basicPercentage(int? basicPercentage) =>
      _basicPercentage = basicPercentage;
  int? get emergencyPercentage => _emergencyPercentage;
  set emergencyPercentage(int? emergencyPercentage) =>
      _emergencyPercentage = emergencyPercentage;
  int? get medicalPercentage => _medicalPercentage;
  set medicalPercentage(int? medicalPercentage) =>
      _medicalPercentage = medicalPercentage;
  int? get totalPercentage => _totalPercentage;
  set totalPercentage(int? totalPercentage) =>
      _totalPercentage = totalPercentage;
  List<String>? get accessToken => _accessToken;
  set accessToken(List<String>? accessToken) => _accessToken = accessToken;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _login = json['login'];
    _userId = json['user_id'];
    _userToken = json['user_token'];
    _qrUrl = json['qr_url'];
    _specialPackage = json['special_package'].cast<String>();
    if (json['child_members'] != null) {
      _childMembers = <ChildMembers>[];
      json['child_members'].forEach((v) {
        _childMembers!.add(ChildMembers.fromJson(v));
      });
    }
    _age = json['age'];
    _userFirstName = json['user_first_name'];
    _userLastName = json['user_last_name'];
    _basicPercentage = json['basic_percentage'];
    _emergencyPercentage = json['emergency_percentage'];
    _medicalPercentage = json['medical_percentage'];
    _totalPercentage = json['total_percentage'];
    _accessToken = json['access_token'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['login'] = _login;
    data['user_id'] = _userId;
    data['user_token'] = _userToken;
    data['qr_url'] = _qrUrl;
    data['special_package'] = _specialPackage;
    if (_childMembers != null) {
      data['child_members'] = _childMembers!.map((v) => v.toJson()).toList();
    }
    data['age'] = _age;
    data['user_first_name'] = _userFirstName;
    data['user_last_name'] = _userLastName;
    data['basic_percentage'] = _basicPercentage;
    data['emergency_percentage'] = _emergencyPercentage;
    data['medical_percentage'] = _medicalPercentage;
    data['total_percentage'] = _totalPercentage;
    data['access_token'] = _accessToken;
    return data;
  }
}

class ChildMembers {
  String? _memberEhId;
  String? _groupId;
  String? _relation;
  int? _active;
  String? _modifiedOn;
  String? _userFirstName;
  String? _userLastName;
  String? _profileImage;

  ChildMembers(
      {String? memberEhId,
      String? groupId,
      String? relation,
      int? active,
      String? modifiedOn,
      String? userFirstName,
      String? userLastName,
      String? profileImage}) {
    if (memberEhId != null) {
      _memberEhId = memberEhId;
    }
    if (groupId != null) {
      _groupId = groupId;
    }
    if (relation != null) {
      _relation = relation;
    }
    if (active != null) {
      _active = active;
    }
    if (modifiedOn != null) {
      _modifiedOn = modifiedOn;
    }
    if (userFirstName != null) {
      _userFirstName = userFirstName;
    }
    if (userLastName != null) {
      _userLastName = userLastName;
    }
    if (profileImage != null) {
      _profileImage = profileImage;
    }
  }

  String? get memberEhId => _memberEhId;
  set memberEhId(String? memberEhId) => _memberEhId = memberEhId;
  String? get groupId => _groupId;
  set groupId(String? groupId) => _groupId = groupId;
  String? get relation => _relation;
  set relation(String? relation) => _relation = relation;
  int? get active => _active;
  set active(int? active) => _active = active;
  String? get modifiedOn => _modifiedOn;
  set modifiedOn(String? modifiedOn) => _modifiedOn = modifiedOn;
  String? get userFirstName => _userFirstName;
  set userFirstName(String? userFirstName) => _userFirstName = userFirstName;
  String? get userLastName => _userLastName;
  set userLastName(String? userLastName) => _userLastName = userLastName;
  String? get profileImage => _profileImage;
  set profileImage(String? profileImage) => _profileImage = profileImage;

  ChildMembers.fromJson(Map<String, dynamic> json) {
    _memberEhId = json['member_eh_id'];
    _groupId = json['group_id'];
    _relation = json['relation'];
    _active = json['active'];
    _modifiedOn = json['modified_on'];
    _userFirstName = json['user_first_name'];
    _userLastName = json['user_last_name'];
    _profileImage = json['profile_image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['member_eh_id'] = _memberEhId;
    data['group_id'] = _groupId;
    data['relation'] = _relation;
    data['active'] = _active;
    data['modified_on'] = _modifiedOn;
    data['user_first_name'] = _userFirstName;
    data['user_last_name'] = _userLastName;
    data['profile_image'] = _profileImage;
    return data;
  }
}
